#!/bin/bash

docker compose down

cd account-service
hy docker build -r pointw
cd ../event-service
hy docker build -r pointw
cd ../registration-service
hy docker build -r pointw
cd ../venue-service
hy docker build -r pointw
