name: event-buddy

services:
  venue-service:
    image: pointw/venue-service
    container_name: venue-service
    ports:
      - "2113:80"
    environment:
      AUTH_ADD_BASIC: true
      HY_INSTANCE_NAME: venue-service development container
      MONGO_HOST: demo-mongo
      MONGO_DBNAME: event-buddy
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
      HY_GATEWAY_URL: http://api-gateway
      HY_BASE_URL: http://$IP_ADDRESS:2113
    depends_on:
      - api-gateway
      - demo-mongo

  registration-service:
    image: pointw/registration-service
    container_name: registration-service
    ports:
      - "2114:80"
    environment:
      AUTH_ADD_BASIC: true
      HY_INSTANCE_NAME: registration-service development container
      MONGO_HOST: demo-mongo
      MONGO_DBNAME: event-buddy
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
      HY_GATEWAY_URL: http://api-gateway
      HY_BASE_URL: http://$IP_ADDRESS:2114
    depends_on:
      - api-gateway
      - demo-mongo

  event-service:
    image: pointw/event-service
    container_name: event-service
    ports:
      - "2115:80"
    environment:
      AUTH_ADD_BASIC: true
      HY_INSTANCE_NAME: event-service development container
      MONGO_HOST: demo-mongo
      MONGO_DBNAME: event-buddy
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
      HY_GATEWAY_URL: http://api-gateway
      HY_BASE_URL: http://$IP_ADDRESS:2115
    depends_on:
      - api-gateway
      - demo-mongo

  account-service:
    image: pointw/account-service
    container_name: account-service
    ports:
      - "2116:80"
    environment:
      AUTH_ADD_BASIC: true
      HY_INSTANCE_NAME: account-service development container
      MONGO_HOST: demo-mongo
      MONGO_DBNAME: event-buddy
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
      HY_GATEWAY_URL: http://api-gateway
      HY_BASE_URL: http://$IP_ADDRESS:2116
    depends_on:
      - api-gateway
      - demo-mongo

  api-gateway:
    image: pointw/hypermea-gateway:0.9.3
    container_name: api-gateway
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: api-gateway development container
      HY_MONGO_HOST: demo-mongo
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
      GW_CURIES_NAMESPACE_URI: uri://event-buddy.pointw.com
    depends_on:
      - demo-mongo

  demo-mongo:
    image: mongo
    container_name: demo-mongo
    ports:
      - "27017:27017"
