name: venue-service

services:
  venue-service:
    image: venue-service
    container_name: venue-service
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: venue-service development container
      MONGO_HOST: venue-service-mongo
      HY_SERVICE_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    depends_on:
      - venue-service-mongo

  venue-service-mongo:
    image: mongo
    container_name: venue-service-mongo
    volumes:
      - venue-service-mongodb:/data/db
      - venue-service-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     venue-service-mongodb:
     venue-service-mongodb_config:
