@startuml
hide <<resource>> circle
hide <<remote>> circle
hide members 

skinparam class {
    BackgroundColor<<remote>> LightBlue
}

class events <<resource>>
class registrations <<remote>>
class venue <<remote>>

events ||-right-o{ registrations
venue ||-down-o{ events
@enduml
