version: '3'
name: events-service

services:
  events-service:
    image: events-service
    container_name: events-service
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: events-service development container
      HY_MONGO_HOST: events-service-mongo
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    volumes:
    - ./logging:/var/log/events-service
    depends_on:
      - events-service-mongo

  events-service-mongo:
    image: mongo
    container_name: events-service-mongo
    volumes:
      - events-service-mongodb:/data/db
      - events-service-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     events-service-mongodb:
     events-service-mongodb_config:
