version: '3'
name: registrations-service

services:
  registrations-service:
    image: registrations-service
    container_name: registrations-service
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: registrations-service development container
      HY_MONGO_HOST: registrations-service-mongo
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    volumes:
    - ./logging:/var/log/registrations-service
    depends_on:
      - registrations-service-mongo

  registrations-service-mongo:
    image: mongo
    container_name: registrations-service-mongo
    volumes:
      - registrations-service-mongodb:/data/db
      - registrations-service-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     registrations-service-mongodb:
     registrations-service-mongodb_config:
