name: event-buddy

services:
  event-buddy:
    image: pointw/event-buddy
    container_name: event-buddy
    ports:
      - "2112:80"
    environment:
      AUTH_ADD_BASIC: true
      HY_INSTANCE_NAME: event-buddy demo
      HY_MONGO_HOST: event-buddy-mongo
      HY_API_PORT: 80
    depends_on:
      - event-buddy-mongo

  event-buddy-mongo:
    image: mongo
    container_name: event-buddy-mongo
    ports:
      - "27017:27017"
