name: event-buddy

services:
  event-buddy:
    image: event-buddy
    container_name: event-buddy
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: event-buddy development container
      MONGO_HOST: event-buddy-mongo
      HY_SERVICE_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    depends_on:
      - event-buddy-mongo

  event-buddy-mongo:
    image: mongo
    container_name: event-buddy-mongo
    ports:
      - "27017:27017"
