version: '3'
name: accounts-service

services:
  accounts-service:
    image: accounts-service
    container_name: accounts-service
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: accounts-service development container
      HY_MONGO_HOST: accounts-service-mongo
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    volumes:
    - ./logging:/var/log/accounts-service
    depends_on:
      - accounts-service-mongo

  accounts-service-mongo:
    image: mongo
    container_name: accounts-service-mongo
    volumes:
      - accounts-service-mongodb:/data/db
      - accounts-service-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     accounts-service-mongodb:
     accounts-service-mongodb_config:
