version: '3'
name: venues-service

services:
  venues-service:
    image: venues-service
    container_name: venues-service
    build: .
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: venues-service development container
      HY_MONGO_HOST: venues-service-mongo
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    volumes:
    - ./logging:/var/log/venues-service
    depends_on:
      - venues-service-mongo

  venues-service-mongo:
    image: mongo
    container_name: venues-service-mongo
    volumes:
      - venues-service-mongodb:/data/db
      - venues-service-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     venues-service-mongodb:
     venues-service-mongodb_config:
